#!/usr/bin/env python3

import argparse
import base64
import pathlib
import json

parser = argparse.ArgumentParser()
parser.add_argument("--registry","-r", help="Registry URL", required=True)
parser.add_argument("--username", "-u", help="Username for registry", required=True)
parser.add_argument("--password", "-p", help="Password for registry", required=True)

args = parser.parse_args()

"""
Output JSON as such:
{
  "auths": {
    "my-registry-url": {
      "auth": base64(username:password)
    }
  }
}
"""

my_json = {
  "auths": {
    args.registry: {
        "auth": str(
            base64.b64encode(
                "{}:{}"
                .format(args.username, args.password)
                .encode("ascii")
            )
        ),
    }
  }
}

"""
Write to $HOME/.docker/config.json
"""

config_path = pathlib.Path.home().joinpath("config.json")

with open(config_path, "w") as f:
    f.write(json.dumps(my_json))
